language: node_js
node_js:
        - 10
branchs:
        only:
        - master
cache:
        directories:
        - node_modules
before_install:
        - export TZ='Asia/Xiamen'        
install: 
        - npm install
script:
        - npm run demo
        - npm run build
after_success:
        - npm run test
deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: ./dist/
        target-branch: gh-pages
        verbose: true
        on:
                branch: master


