language: node_js
node_js:
        - 10
branches:
        only:
        - master
cache:
        directories:
        - node_modules
before_install:
        - export TZ='Asia/Xiamen'        
install: 
        - npm install
script:
        - npm run demo
        - npm run build
after_success:
        - npm run test
deploy:
        provider: pages
        cleanup: true
        token: $GITHUB_TOKEN
        local_dir: ./dist/
        target_branch: gh-pages
        verbose: true
        on:
                branch: master


